[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/heads/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/terminfo/alacritty.info"]
    type = "file"
    url = "https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info"
[".local/share/terminfo/ncurses-src.info"]
    type = "file"
    url = "https://raw.githubusercontent.com/mirror/ncurses/master/misc/terminfo.src"
